#pragma once
// SCREEN
#define WIDTH 1280
#define HEIGHT 720
// MAP
#define CELL_SIZE 32
#define MAP_WIDTH 40
#define MAP_HEIGHT 23
// CAMERA
#define BASE_ZOOM 2.0f
#define ZOOM_SPEED 5
#define SIGHT_RADIUS 150
// PLAYER
#define WALK_SPEED 200.0f
#define SHIP_SPEED 300.0f
// ENEMIES
#define FEAR_RADIUS 100
#define ENEMY_BASE_SPEED 100.0f
#define DROP_COOLDOWN 7
#define ENEMY_POINTS 50
// TRASH
#define TRASH_BASE_SPEED 60.0f
#define TRASH_POINTS 10
#define TRASH_POINTS_PENALTY 100

